[package]
name = "devkit"
author = "Joh R. McGuinness"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3" # Command line parsing crate
sys-info = "0.9.0"